config/routes.rb
Rails.application.routes.draw do
  get '/books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get '/top' => 'homes#top'
  root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed"
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
    <ur>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ur>
  <% end %>
  <h1>Editing Book</h1>
  <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <div>Title</div>
    <%= f.text_field :title %>

  <div>Body</div>
    <%= f.text_area :body %>

  <p><%= f.submit 'Update Book' %></p>

  <%= link_to "Show", book_path(@book) %>
  |
  <%= link_to "Back", "/books" %>

  <% end %>
</body>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<h2>Books</h2>

<body>
  <table>
    <tr>
      <th>Title</th>
      <th>body</th>
      <th colspan ="3"></th>
    </tr>

    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>

      <td><%= link_to "Show", book_path(book) %></td>
      <td><%= link_to "Edit", edit_book_path(book) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
    <% end %>

  </table>
</body>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ur>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ur>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <div>Title</div>
  <%= f.text_field :title %>

  <div>Body</div>
  <%= f.text_area :body %>

  <p><%= f.submit 'Create Book' %></P>
<% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<body>
  <p><strong>Title:</strong> <%= @book.title %></p>

  <p><strong>Body:</strong> <%= @book.body %></p>

  <%= link_to "Edit", edit_book_path(@book.id) %>
  |
  <%= link_to "Back", "/books" %>
</body>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ!</h1>
  <p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
  <%= link_to "Start", "/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<body>
  <h1>Editing Book</h1>
  <%= form_with model: @list, url: update_list_path(@list.id), method: :patch do |f| %>

  <div>Title</div>
    <%= f.text_field :title %>

  <div>Body</div>
    <%= f.text_area :body %>

  <p><%= f.submit 'Update Book' %></p>

  <%= link_to "Show", list_path(@list) %>
  |
  <%= link_to "Back", "/lists/index" %>

  <% end %>
</body>

app/views/lists/new.html.erb
<div>
  <%= flash[:notice] %>
</div>
<h2>Books</h2>

<body>
  <table>
    <tr>
      <th>Title</th>
      <th>body</th>
      <th colspan ="3"></th>
    </tr>

    <% @lists.each do |list| %>
    <tr>
      <td><%= list.title %></td>
      <td><%= list.body %></td>

      <td><%= link_to "Show", list_path(list) %></td>
      <td><%= link_to "Edit", edit_list_path(list) %></td>
      <td><%= link_to "Destroy", destroy_list_path(list), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
    <% end %>

  </table>
</body>

<h2>New book</h2>
<% if @list.errors.any? %>
  <%= @list.errors.count %>errors prohibited this book from being saved:
  <ur>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ur>
<% end %>

<%= form_with model: @list, url: '/lists', method: :post do |f| %>
  <div>Title</div>
  <%= f.text_field :title %>

  <div>Body</div>
  <%= f.text_area :body %>

  <p><%= f.submit 'Create Book' %></P>
<% end %>